CREATE TABLE Clientes(
	CLIENTE_id INT,
    Nombre_completo (text(20)),
    telefono int,
    DNI INT,
    FECHA_NAC DATE,
    MAIL VARCHAR(60),
    MAIL VARCHAR(60),
    SALDO_INVERTIDO DECIMAL(20,2),
    PERFIL_INVERSOR INT,
    INGRESOS_MENSUALES DECIMAL(20,2)
    RENTABILIDAD_DEL_CLIENTE DECIMAL(20,2)
    PRIMARY KEY(CLIENTE_ID)
    );