-- MySQL Script generated by MySQL Workbench
-- Wed Feb 22 22:23:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Tp_defederico
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Tp_defederico` ;

-- -----------------------------------------------------
-- Schema Tp_defederico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Tp_defederico` DEFAULT CHARACTER SET utf8 ;
USE `Tp_defederico` ;

-- -----------------------------------------------------
-- Table `Tp_defederico`.`Clientessss`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tp_defederico`.`Clientessss` (
  `id_Cliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Completo` VARCHAR(45) NOT NULL,
  `Telefono` INT NOT NULL,
  `DNI` INT NOT NULL,
  `FECHA_NACIMIENTO` DATE NOT NULL,
  `MAIL` VARCHAR(45) NOT NULL,
  `SALDO_INVERTIDO` DECIMAL(20,2) NOT NULL,
  `PERFIL_DEL_INVERSOR` INT NOT NULL,
  `INGRESOS_MENSUALES` DECIMAL(20,2) NOT NULL,
  `RENTABILIDAD_CLIENTE` DECIMAL(20,2) NOT NULL,
  PRIMARY KEY (`id_Cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tp_defederico`.`Acciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tp_defederico`.`Acciones` (
  `Accion_id` INT NOT NULL AUTO_INCREMENT,
  `Nombre_acciones` VARCHAR(45) NOT NULL,
  `open_acciones` DECIMAL(20,2) NOT NULL,
  `Close_acciones` DECIMAL(20,2) NOT NULL,
  `Fecha_acciones` DATETIME NOT NULL,
  `High_acciones` DECIMAL(20,2) NOT NULL,
  `Media_acciones` DECIMAL(20,2) NOT NULL,
  `Low_acciones` DECIMAL(20,2) NOT NULL,
  `Precio_acciones` INT NOT NULL,
  `Premarket_acciones` DECIMAL(20,2) NOT NULL,
  `Market_Cap_acciones` DECIMAL(20,2) NOT NULL,
  PRIMARY KEY (`Accion_id`),
  CONSTRAINT `Precio_operacion`
    FOREIGN KEY (`Precio_acciones`)
    REFERENCES `Tp_defederico`.`OPERACIONES` (`OPERACION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Precio_operacion_idx` ON `Tp_defederico`.`Acciones` (`Precio_acciones` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Tp_defederico`.`Criptomonedas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tp_defederico`.`Criptomonedas` (
  `id__Criptomoneda` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Criptomoneda` VARCHAR(45) NOT NULL,
  `open__Criptomoneda` DECIMAL(20,2) NOT NULL,
  `Close_Criptomoneda` DECIMAL(20,2) NOT NULL,
  `Fecha_Criptomoneda` DATETIME NOT NULL,
  `High_Criptomoneda` DECIMAL(20,2) NOT NULL,
  `Media_Criptomoneda` DECIMAL(20,2) NOT NULL,
  `Low_Criptomoneda` DECIMAL(20,2) NOT NULL,
  `Precio_Criptomoneda` INT NOT NULL,
  `Market_Cap_Criptomoneda` DECIMAL(20,2) NOT NULL,
  PRIMARY KEY (`id__Criptomoneda`),
  CONSTRAINT `Precio_operacion`
    FOREIGN KEY (`Precio_Criptomoneda`)
    REFERENCES `Tp_defederico`.`OPERACIONES` (`OPERACION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Precio_Criptomoneda_idx` ON `Tp_defederico`.`Criptomonedas` (`Precio_Criptomoneda` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Tp_defederico`.`Fondo_Comun_de_inversion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tp_defederico`.`Fondo_Comun_de_inversion` (
  `Fci_id` INT NOT NULL,
  `Nombre_fci` VARCHAR(45) NOT NULL,
  `Open_fci` DECIMAL(20,2) NOT NULL,
  `Close_fci` DECIMAL(20,2) NOT NULL,
  `Fecha_fci` DATETIME NOT NULL,
  `High_fci` DECIMAL(20,2) NOT NULL,
  `Media_fci` DECIMAL(20,2) NOT NULL,
  `Low_fci` DECIMAL(20,2) NOT NULL,
  `Precio_cuotaparte_fci` INT NOT NULL,
  `Cuotapartes_total_fci` DECIMAL(20,2) NOT NULL,
  PRIMARY KEY (`Fci_id`),
  CONSTRAINT `Precio_operacion`
    FOREIGN KEY (`Precio_cuotaparte_fci`)
    REFERENCES `Tp_defederico`.`OPERACIONES` (`OPERACION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Precio_operacion_idx` ON `Tp_defederico`.`Fondo_Comun_de_inversion` (`Precio_cuotaparte_fci` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Tp_defederico`.`Seguros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tp_defederico`.`Seguros` (
  `id_seguro` INT NOT NULL AUTO_INCREMENT,
  `Nombre_seguro` VARCHAR(45) NOT NULL,
  `Fecha_seguro` DATETIME NOT NULL,
  `Precio_inicial_seguro` INT NOT NULL,
  `Precio_final_seguro` INT NOT NULL,
  `Market_Cap` DECIMAL(20,2) NOT NULL,
  `Tipo_seguro` TEXT(20) NOT NULL,
  `Accion_id_seguro` INT NOT NULL,
  `Criptomoneda_id_seguro` INT NOT NULL,
  PRIMARY KEY (`id_seguro`),
  CONSTRAINT `Criptomoneda_id`
    FOREIGN KEY (`Criptomoneda_id_seguro`)
    REFERENCES `Tp_defederico`.`Criptomonedas` (`id__Criptomoneda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `accion_id`
    FOREIGN KEY (`Accion_id_seguro`)
    REFERENCES `Tp_defederico`.`Acciones` (`Accion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Precio_operacion`
    FOREIGN KEY (`Precio_inicial_seguro`)
    REFERENCES `Tp_defederico`.`OPERACIONES` (`OPERACION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Precio_operacion`
    FOREIGN KEY (`Precio_final_seguro`)
    REFERENCES `Tp_defederico`.`OPERACIONES` (`OPERACION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Criptomoneda_id_idx` ON `Tp_defederico`.`Seguros` (`Criptomoneda_id_seguro` ASC) VISIBLE;

CREATE INDEX `accion_id_idx` ON `Tp_defederico`.`Seguros` (`Accion_id_seguro` ASC) VISIBLE;

CREATE INDEX `Precio_operacion_idx` ON `Tp_defederico`.`Seguros` (`Precio_inicial_seguro` ASC) VISIBLE;

CREATE INDEX `Precio_operacion_idx1` ON `Tp_defederico`.`Seguros` (`Precio_final_seguro` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Tp_defederico`.`Divisas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tp_defederico`.`Divisas` (
  `Divisas_id` INT NOT NULL AUTO_INCREMENT,
  `Nombre_divisas` VARCHAR(45) NOT NULL,
  `Open_divisas` DECIMAL(20,2) NOT NULL,
  `Close_divisas` DECIMAL(20,2) NOT NULL,
  `Fecha_divisas` DATETIME NOT NULL,
  `High_divisas` DECIMAL(20,2) NOT NULL,
  `Media_divisas` DECIMAL(20,2) NOT NULL,
  `Low_divisas` DECIMAL(20,2) NOT NULL,
  `Precio_divisas` INT NOT NULL,
  `Premarket_divisas` DECIMAL(20,2) NOT NULL,
  `Market_Cap_divisas` DECIMAL(20,2) NOT NULL,
  PRIMARY KEY (`Divisas_id`),
  CONSTRAINT `Precio`
    FOREIGN KEY ()
    REFERENCES `Tp_defederico`.`OPERACIONES` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `precio_opercaion`
    FOREIGN KEY (`Precio_divisas`)
    REFERENCES `Tp_defederico`.`OPERACIONES` (`OPERACION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `precio_opercaion_idx` ON `Tp_defederico`.`Divisas` (`Precio_divisas` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Tp_defederico`.`OPERACIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tp_defederico`.`OPERACIONES` (
  `OPERACION_ID` INT NOT NULL AUTO_INCREMENT,
  `Tipo_operacion` TEXT(20) NOT NULL,
  `Precio_operacion` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Accion_id` INT NOT NULL,
  `Cliente_id` INT NOT NULL,
  `Criptomoneda_id` INT NOT NULL,
  `FCI_ID` INT NOT NULL,
  `SEGURO_ID` INT NOT NULL,
  `DIVISA_ID` INT NOT NULL,
  PRIMARY KEY (`OPERACION_ID`),
  CONSTRAINT `Accion_id`
    FOREIGN KEY (`OPERACION_ID`)
    REFERENCES `Tp_defederico`.`Acciones` (`Accion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Cliente_id`
    FOREIGN KEY (`Cliente_id`)
    REFERENCES `Tp_defederico`.`Clientessss` (`id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Criptomoneda_id`
    FOREIGN KEY (`Criptomoneda_id`)
    REFERENCES `Tp_defederico`.`Criptomonedas` (`id__Criptomoneda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fci_id`
    FOREIGN KEY (`FCI_ID`)
    REFERENCES `Tp_defederico`.`Fondo_Comun_de_inversion` (`Fci_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `seguro_id`
    FOREIGN KEY (`SEGURO_ID`)
    REFERENCES `Tp_defederico`.`Seguros` (`id_seguro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `divisa_id`
    FOREIGN KEY (`DIVISA_ID`)
    REFERENCES `Tp_defederico`.`Divisas` (`Divisas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Accion_id`
    FOREIGN KEY (`Accion_id`)
    REFERENCES `Tp_defederico`.`Acciones` (`Accion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Cliente_id_idx` ON `Tp_defederico`.`OPERACIONES` (`Cliente_id` ASC) VISIBLE;

CREATE INDEX `Criptomoneda_id_idx` ON `Tp_defederico`.`OPERACIONES` (`Criptomoneda_id` ASC) VISIBLE;

CREATE INDEX `Fci_id_idx` ON `Tp_defederico`.`OPERACIONES` (`FCI_ID` ASC) VISIBLE;

CREATE INDEX `seguro_id_idx` ON `Tp_defederico`.`OPERACIONES` (`SEGURO_ID` ASC) VISIBLE;

CREATE INDEX `divisa_id_idx` ON `Tp_defederico`.`OPERACIONES` (`DIVISA_ID` ASC) VISIBLE;

CREATE INDEX `Accion_id_idx` ON `Tp_defederico`.`OPERACIONES` (`Accion_id` ASC) VISIBLE;

CREATE USER 'user1';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
